version: '3'

networks:
  homelab_net:
    external: true
    name: ${MAIN_NETWORK}

volumes:
  homepage-data:
  traefik_config:


name: homelab_main

services:
  traefik:
    image: traefik:v2.9
    restart: always
    env_file:
      - .env
    networks:
      - homelab_net
    command:
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.docker=true"
      - "--serversTransport.insecureSkipVerify=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/configuration/traefik.yaml"
      - "--providers.file.watch=true"
    volumes:
      - "traefik_config:/configuration"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      # ----------- HOMEPAGE LABELS ----------
      - homepage.group=Administration
      - homepage.name=Traefik Dashboard
      - homepage.href=https://${DASHBOARD_HOST}
      - homepage.icon=traefik
      - homepage.widget.type=traefik
      - homepage.widget.url=https://${DASHBOARD_HOST}

      # ----------- TRAEFIK LABELS ----------
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-http.entrypoints=websecure"
      - "traefik.http.routers.dashboard-http.rule=Host(`${DASHBOARD_HOST}`)"
      - "traefik.http.services.dashboard-http.loadbalancer.server.port=8080"
    ports:
      - "${MAIN_PORT}:80"
      - "${TLS_PORT}:443"
      # - "${DASHBOARD_PORT}:8080"


  homepage:
    # HOMEPAGE DASHBOARD
    # see https://gethomepage.dev/v0.7.4/configs/docker/#using-socket-directly
    # for configuring auto sevice dicovery using docker 
    # both the volume /var/run/docker.sock and the docker.yaml config file need to be set
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    environment:
      - LOG_LEVEL=debug
    labels:
      # -------------- TRAEFIK LABELS ---------
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-http.entrypoints=websecure"
      - "traefik.http.routers.homepage-http.rule=Host(`${HOMEPAGE_HOST}`)"
      - "traefik.http.services.homepage-http.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage-http.tls=true"
    volumes:
      - homepage-data:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    networks:
      - homelab_net
