version: '3'

networks:
  homelab_net:
    external: true
    name: ${MAIN_NETWORK}

volumes:
  homepage-data:


name: homelab_main

services:
  traefik:
    image: traefik:v2.9
    restart: always
    env_file:
      - .env
    networks:
      - homelab_net
    command:
      - "--api.insecure=true"
      - "--entryPoints.web.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      # - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      # - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - homepage.group=Administation
      - homepage.name=Traefik Dashboard
      - homepage.href=http://${DASHBOARD_HOST}
      - homepage.icon=traefik

      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-http.entrypoints=web"
      - "traefik.http.routers.dashboard-http.rule=Host(`${DASHBOARD_HOST}`)"
      - "traefik.http.services.dashboard-http.loadbalancer.server.port=8080"
    ports:
      - "${MAIN_PORT}:80"
      - "${DASHBOARD_PORT}:8080"
      # - "443:443"


  homepage:
    # HOMEPAGE DASHBOARD
    # see https://gethomepage.dev/v0.7.4/configs/docker/#using-socket-directly
    # for configuring auto sevice dicovery using docker 
    # both the volume /var/run/docker.sock and the docker.yaml config file need to be set
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    environment:
      - LOG_LEVEL=debug
    labels:
      # -------------- TRAEFIK LABELS ---------
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-http.entrypoints=web"
      - "traefik.http.routers.homepage-http.rule=Host(`${HOMEPAGE_HOST}`)"
      - "traefik.http.services.homepage-http.loadbalancer.server.port=3000"
    volumes:
      - homepage-data:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    networks:
      - homelab_net
