version: '3'

name: excalidraw_homelab

networks:
  excalidraw_net:
    external: true
    name: ${MAIN_NETWORK}

services:
  excalidraw:
    restart: always
    image: excalidraw/excalidraw:latest
    networks:
      - excalidraw_net
    labels:
      # ------------------ TRAEFIK LABELS -----------------------
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw-http.entrypoints=web"
      - "traefik.http.routers.excalidraw-http.rule=Host(`${EXCALIDRAW_HOST}`)"
      - "traefik.http.services.excalidraw-http.loadbalancer.server.port=80"

      # ------------------ HOMEPAGE LABELS -----------------------
      - homepage.group=Design
      - homepage.name=Excalidraw
      - homepage.href=http://${EXCALIDRAW_HOST}:${MAIN_PORT}
      - homepage.icon=excalidraw.png
